### ISSUE TITLE
More snippet info

### ISSUE THREAD

**Issue by btcrooks** [rawcodeio/Feature-Request#4]
It would be cool to possibly have the date the snippet was posted along with the uploader's username for public snippets.

**Comment by BenMann** [comment]
Hey, thanks for the idea.  
Date is planned and already in the database for every snippet (in other words, easy to display). Some changes to the frontend will be realized soon, which also includes always visible descriptions. Getting the owners name might require a second query, which I'll have to think about a little more 😋. Im planning to display users a little more prominently anyway, so I'm all for it.

**Comment by BenMann** [comment]
Done :] 
User specific stuff will come at a later point.
![bildschirmfoto 2015-11-02 um 19 35 46](https://cloud.githubusercontent.com/assets/7561396/10890568/f373d918-8198-11e5-8ccf-c8fd0fa47714.png)

**Comment by btcrooks** [comment]
Beautiful ;)
